# Generated by Django 6.0.4 on 2026-04-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_en', models.CharField(max_length=100)),
                ('crop_name_ta', models.CharField(max_length=100)),
                ('price_per_quintal', models.IntegerField()),
                ('trend', models.CharField(max_length=20)),
                ('is_up', models.BooleanField(default=True)),
            ],
        ),
    ]
